server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:h2:mem:notificationdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  h2:
    console:
      enabled: true
  boot:
    admin:
      client:
        url: http://localhost:8099
        username: admin
        password: admin
        instance:
          name: ${spring.application.name}
          prefer-ip: true
          metadata:
            tags:
              environment: local

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers
  endpoint:
    health:
      show-details: always
      show-components: always
      probes:
        enabled: true
      group:
        liveness:
          include: livenessState,diskSpace
          show-details: always
        readiness:
          include: readinessState,db,telemetryService
          show-details: always
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  info:
    env:
      enabled: true
    git:
      enabled: true
      mode: full

info:
  app:
    name: ${spring.application.name}
    description: Notification service — manages email and SMS notifications for orders and payments
    version: 1.0.0

downstream:
  telemetry-service:
    url: http://localhost:8086

logging:
  level:
    com.ecommerce.notificationservice: DEBUG
